# Common sections
defaults: &defaults
  working_directory: ~/aur
  docker:
    - image: jfchevrette/aur-builder

updatepackage: &updatepackage
  name: Update packages
  command: sudo pacman -Syu --noconfirm

installyay: &installmakedepswithyay
  name: install yay & makedepends with it
  command: |
    git clone https://aur.archlinux.org/yay.git
    cd yay
    sudo -u builder makepkg -sif --noconfirm
    cd ~/aur/${CIRCLE_JOB}
    source PKGBUILD
    echo "Will install makedepends: ${makedepends[@]}"
    yay -Sy --noconfirm --useask ${makedepends[@]}

gitupdate: &gitupdate
  name: Git repo updates
  command: |
    sed -i "s#ssh+git://aur@aur.archlinux.org#https://aur.archlinux.org#" .gitmodules
    git submodule update --init

pkgbuildtest: &pkgbuildtest
  name: Testing PKGBUILD
  command: |
    cd ~/aur/${CIRCLE_JOB}
    namcap PKGBUILD

buildtest: &buildtest
  name: Building package
  command: |
    cd ~/aur/${CIRCLE_JOB}
    makepkg -sci --noconfirm

# Main
version: 2
jobs:
  gojsontoyaml-git:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  istio-bin:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  kapp-git:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *installmakedepswithyay
      - run:
          <<: *buildtest
  mtail-bin:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  operator-sdk:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  ytt:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
  ytt-git:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
workflows:
  version: 2
  build:
    jobs:
      - gojsontoyaml-git
      - istio-bin
      - kapp-git
      - mtail-bin
      - operator-sdk
      - ytt
      - ytt-git
